version: "3.8"

services:
  app:
    container_name: news-app
    image: news-app
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
